apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  # Encypted Secrets with the highest level, fallback on 
  - resources:      
      - secrets
    providers:
      - kms:
          apiVersion: v2
          name: cloudKMSProviderPlugin
          endpoint: unix:///tmp/kms/socketfile.sock
          timeout: 3s      
      - kms:
          name: localVault
          endpoint: unix:///tmp/localkms/socketfile.sock
          cachesize: 100
      - identity: {}
  # Keep Events and ConfigMaps unencrypted
  - resources:
      - events
      - configmaps
    providers:
      - identity: {}
  # Encypted Secrets with the highest level 
  - resources:
      - '*.*' # wildcard matching supported in Kubernetes 1.27 or higher
    providers:
      - kms:
          name: localVault
          endpoint: unix:///tmp/localkms/socketfile.sock
          cachesize: 100
      - identity: {}


