apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: local
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: sdepuser
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: <REPLACE WITH PASSWORD SET EARLIER>
  RCLONE_CONFIG_S3_ENDPOINT: http://my-mlflow-minio.default.svc.cluster.local:80      
  RCLONE_CONFIG_S3_ENV_AUTH: "false"