apiVersion: batch/v1
kind: Job
metadata:
  name: model-custom-metrics-runs
spec:
  template:
    spec:
      containers:
      - name: model-custom-metrics-runs
        image: model-custom-metrics-runs:latest
        imagePullPolicy: IfNotPresent
        command: ["python3",  "model-custom-metrics-runs.py"]
        env:
        # Define the environment variable for MLFlow Tracking Server IP or Serivce Name
        - name: MLFLOW_SERVER_IP
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              # MLFlow Tracking Server IP or Service Name
              key: mlflow-server.ip
        # Define the environment variable for MLFlow Tracking Server Port
        - name: MLFLOW_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              # MLFlow Tracking Server Port
              key: mlflow-server.port
      restartPolicy: Never
  backoffLimit: 4
