apiVersion: v1
kind: Service
metadata:
  name: hello-scaling-svc
spec:
  type: NodePort
  selector:
    app: hello-scaling
  ports:
     - protocol: TCP  
       nodePort: 31000
       port: 80
       targetPort: http