apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-scaling-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-scaling
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50