apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: appxadmin
spec:
  groups:
  - system:authenticated
  request: 
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth