apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: appx-admin-role
rules:
- apiGroups: [""] 
  resources: ["pods","deployments","services","configmaps"]
  verbs: ["*"]
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["list"]