apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appx-admin-rolebinding
  namespace: default
subjects:
- kind: User
  name: appxadmin #Same user created in our context
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # Here we link the user with the role defined in the role YAML
  kind: Role 
  name: appx-admin-role
  apiGroup: rbac.authorization.k8s.io